#pragma once

#include <vector>

#include "Node.h"
#include "../World/Map.h"


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                  The base of this code is generated by ChatGPT.                                    //
//                                  It is modified to fit my own purposes.                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


namespace Algorithm
{

    std::vector<Node*> FindPath(int startCol, int startRow, int endCol, int endRow, Game::Map& map);
    int CalculateHeuristic(int col, int row, int endCol, int endRow);
    std::vector<Node*> GetNeighbors(const Node& node, int endCol, int endRow, Game::Map& map);
    void ReconstructPath(Node* node, std::vector<Node*>& path);
    void CleanupNodes(const std::vector<Node*>& nodes);

}