#pragma once

#include <vector>

#include "Node.h"


//////////////////////////////////|################################################|////////////////////////////////////
//                                | The base of this code is generated by ChatGPT. |                                  //
//                                | It is modified to fit my own purposes.         |                                  //
//////////////////////////////////|################################################|////////////////////////////////////


namespace Algorithm
{

    std::vector<std::pair<int, int>> AStar(const std::vector<std::vector<int>>& grid, std::pair<int, int> start, std::pair<int, int> goal);
    int CalculateHeuristic(int col, int row, int endCol, int endRow);

    struct pair_hash
    {
        // Overwrite the function call operator for use as a hash function
        // Overwriting the function call operator allows to call "objects like functions"
        // e.g.
        template <class T1, class T2>
        std::size_t operator () (const std::pair<T1, T2>& p) const
        {
            // Create a hash values for the elements of the pair
            auto h1 = std::hash<T1>{}(p.first);
            auto h2 = std::hash<T2>{}(p.second);

            // Combine both hash values
            // It uses bitwise XOR-operator (^)
            return h1 ^ h2;
        }
    };

}